title: Dave McLaughlin
description: davemaps.com is the online presence of Dave McLaughlin, web developer and GIS graduate student.

author: Dave McLaughlin
permalink: /:categories/:title
theme: jekyll-theme-primer
timezone: America/New_York
url: https://davemaps.com

collections:
  drafts:
    output: true

plugins:
  - jekyll-feed
  
defaults:
  -
    author: Dave McLaughlin
    layout: post
  -
    scope:
      path: ""
      type: drafts
    value:
      layout: draf